name: login

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  check-image:
    runs-on: ubuntu-latest
    steps: 
      - name: 登录 阿里云容器镜像服务
        run: |
          echo "${{ secrets.ALIYUN_ACR_PASSWORD }}" | docker login --username=${{ secrets.ALIYUN_ACR_USERNAME }} --password-stdin crpi-9ovxnbm4ma0mwo5y.cn-chengdu.personal.cr.aliyuncs.com
          